// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ1fDhsgpITY6-wH1-FfEHViBNXs_aank',
    appId: '1:986187033285:web:cecfe8fdb4168de46f9eac',
    messagingSenderId: '986187033285',
    projectId: 'flutter-project-488fd',
    authDomain: 'flutter-project-488fd.firebaseapp.com',
    storageBucket: 'flutter-project-488fd.appspot.com',
    measurementId: 'G-DP7MGS6CN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApAMvRXtomR53eY7sUX8zAOZg0u8ueAFg',
    appId: '1:986187033285:android:64b4dc5b712301446f9eac',
    messagingSenderId: '986187033285',
    projectId: 'flutter-project-488fd',
    storageBucket: 'flutter-project-488fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-nhgpS5IicEVDpM1_B_CXElmfl-KLg8k',
    appId: '1:986187033285:ios:f28a58dc11921f996f9eac',
    messagingSenderId: '986187033285',
    projectId: 'flutter-project-488fd',
    storageBucket: 'flutter-project-488fd.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-nhgpS5IicEVDpM1_B_CXElmfl-KLg8k',
    appId: '1:986187033285:ios:f28a58dc11921f996f9eac',
    messagingSenderId: '986187033285',
    projectId: 'flutter-project-488fd',
    storageBucket: 'flutter-project-488fd.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ1fDhsgpITY6-wH1-FfEHViBNXs_aank',
    appId: '1:986187033285:web:3ef56d16e3a5f4b66f9eac',
    messagingSenderId: '986187033285',
    projectId: 'flutter-project-488fd',
    authDomain: 'flutter-project-488fd.firebaseapp.com',
    storageBucket: 'flutter-project-488fd.appspot.com',
    measurementId: 'G-KFRRNQZFSR',
  );
}
